#+title: \textcolor{Blue}{Report for Huawei Technical Project}
#+date: 11.02.2024
#+author: Kadir Gunel, PhD
#+email: kadir.gunel@gmail.com
#+language: en
#+keywords: CTR, MLP, Hyperparameter Optimization
#+options: timestamp:t title:t toc:nil todo:nil |:nil 
#+options: d:(not "LOGBOOK") date:t e:t email:t f:t inline:t num:t


\begin{abstract}
This report intends to provide a quick overview of the tasks accomplished. It covers the data utilized, the preprocessing steps employed, the configuration of the models, and, of course, the results obtained from the models. It also emphasizes the crucial nature of all features in the dataset used for the models. The provided scripts include only model proposals without hyperparameter optimization. Additionally, the scripts do not include KNN search with cosine similarity.

\\
\\
Best Regards 
\end{abstract}


* \textcolor{Maroon}{Data}

For the requested CTR models, [[https://huggingface.co/datasets/reczoo/MovielensLatest_x1][MovieLens]][fn:1] data set is
used. This data set has only 3 features (user_{id}, item_{id} and
tag_{id}) and a binary label set. Its training, validation and test
sets are already prepared. The training set consists of nearly 1.5
Million samples, where as validation and test sets have 400 thousand
and 200 thousand samples. 


** \textcolor{Mahogany}{Pre-processing}

Since the main experiments are dependent to the [[cite:&zhao2022fint]],
their approach is followed. We eliminated the least frequent 10
features and replaced them as the "unknown word" just like in natural
language processing. 


* \textcolor{Maroon}{Experiments}
All conducted experiments are done with either by using all three 
features or  by using only 2 specific features - /user_{id}/ and
/item_{id}/. 

For both experiments, the embedding layers are derived from the
features of training sets - all put inside single embedding layer.

For all the experiments, binary cross entropy is used for minimizing
the error rate. Additionally, the models' performances are tested with
/Area Under the Curve/ (AUC) - in order to see if the model learns to
predict correctly and not by random.

For both models, /FINT/ and MLP, embedding size is set to 16, hidden dimensions
of the DNN classifier is set to 300 just like in the paper. For the
optimizer /Adam/ is used with a learning rate of $1e-3$. Batch sizes
are set to 1024. 




* \textcolor{Maroon}{Results}

Table below \ref{tab:results} shows results for FINT and MLP
models. Note that none of the models perform well when using only
user_{id} and item_{id}[fn:2]. Hence it is decided to show only the
better results.



\begin{table}[htbp]
  \centering
  \begin{tabular}{l|c|c}
   \hline
         & BCE Loss & AUC\\[0pt]
   \hline
   FINT & .247 / .2995 / .2992 & .9564 / .9350 / .9350\\[0pt]
   \hline
   MLP & .2509 / .3132 / .3119 & .9557 / .9308 / .9312\\[0pt]
   \hline
  \end{tabular}
  \caption{Results for the training, validation and test loss and AUC results respectively for FINT and MLP models using all 3 features.}
  \label{tab:results}
\end{table}









* \textcolor{Maroon}{Question #2}

** \textcolor{Mahogany}{Part 1}
Since each model has an embedding layer which include a dedicated user_{id} and
item_{id} vectors. A simple _cosine similarty_ search with k-nearest neighbor
search can be done. For this case k equals to $5$. So given the
user_{id} whole item_{id} embeddings will be searched. And the first 5
of them will be recommended to this specific user.

** \textcolor{Mahogany}{More advanced search : Cross Domain Similarity Local Scaling}

KNN search is fast but it has a severe problem which is called the
hubness problem. [[cite:&DBLP:journals/corr/abs-1710-04087]] tries to
solve this problem by using cross domain similarity search. It is more
costly compared to knn but it finds better candidates. 


* \textcolor{Maroon}{Question #3}

If the model is performing poorly on the production, this might have
different explanations :
1. the model encounters with information that the neither training nor
   the test set has this kind of information 
2. The production data might include too many "unknown words" hence
   the model performs bad.

Solutions:
 - just collect that data and train the model from
   scratch. 



\newpage
\printbibliography

* Footnotes
[fn:2] Their AUC results show that both classifiers behave randomly
when using only these 2 features. 

[fn:1]Downloaded from https://huggingface.co/datasets/reczoo/MovielensLatest_x1 
